### ISSUE TITLE
Add console ability

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin-client#34] opened 2019-07-26 16:49 UTC
Add console ability to existing wallet to allow support for commands not shown on GUI and easy troubleshooting.

**Comment by riordant** [comment] 2019-08-20 17:46
Closing as this is a duplicate of https://github.com/zcoinofficial/zcoin-client/issues/26. Discussion will continue there

**Closed by riordant** 2019-08-20 17:46 UTC
Labels: improvement
