### ISSUE TITLE
Client Sometimes Fails to Realise Mints Are Ready to Send

### ISSUE THREAD

**Issue by sproxet** [zcoinofficial/zcoin-client#46] opened 2019-09-01 18:14 UTC
After 17 confirmation, it still says pending and I can not do private send. When I close the app and open it again, it says that I have 2 zcoin available for private send, but it shows a suggestion for anonymizing coins, when I just did and 50% of my zcoins are already minted.

_Originally posted by @hakonamatata in https://github.com/zcoinofficial/zcoin-client/issues/45#issuecomment-526922117_

**Comment by sproxet** [comment] 2019-09-01 18:21
Ok, so this seems to be two separate issues in its own right. The one this new issue about is that Zcoin Client isn't updating balances properly after mints get the requisite six confirmations.

Unfortunately, I can't seem to reproduce the issue.

@hakonamatata When Zcoin Client told you that you couldn't do a private send, did the error occur when you were entering the amount before you hit the "Send" button, or did the error occur after you had already entered your password?

**Comment by hakonamatata** [comment] 2019-09-02 08:24
The error was that it said 0 XZC available for private send. Since the balances was not updated, even after 17 confirmations. Then you can't click the "send" button at all. 

The issue was resolved as soon as I closed the app and opened it again.

**Comment by riordant** [comment] 2019-09-04 08:41
@hakonamatata I also can't reproduce this (though I'm using regtest mode). However the balance issue is very likely fixed now, and so given that the issue is fixed on a restart, I believe this will be fixed on 0.0.3. It will be released Friday

**Comment by hakonamatata** [comment] 2019-09-09 16:33
Testing version 0.0.3, still the same behavior

![image](https://user-images.githubusercontent.com/4003969/64549043-2a1dd580-d330-11e9-823d-201b63a9cf44.png)

It says 1.95 pending until i close and open the client again.

**Comment by qashban4** [comment] 2019-10-14 05:38
![Zoin Mint](https://user-images.githubusercontent.com/55271754/66731053-8acf8f00-ee55-11e9-934e-7de64ec1ba42.JPG)

@hakonamatata could you please retest on latest GUI wallet https://github.com/zcoinofficial/zcoin-client/releases/tag/v0.0.4-1   . I couldn't reproduce it on latest.

**Comment by riordant** [comment] 2019-10-23 09:16
This is almost certainly fixed now so I think it can be closed.

**Closed by riordant** 2019-10-23 09:16 UTC
Labels: High priority, daemon
