### ISSUE TITLE
Client stuck on "Loading Blockchain"

### ISSUE THREAD

**Issue by catchingknives** [zcoinofficial/zcoin-client#39] opened 2019-08-21 06:55 UTC
OS: macOS Mojave 10.14.6

Possibly related to, if not the same as #36. Left open for 5 minutes but no log activity beyond the initial burst.

Log:
```
2019-08-21T06:50:51.550Z [zcoin:main] info: zcoin paths: { rootFolder: '/Applications/Zcoin Client.app/Contents/Resources/app.asar',
  unpackedRootFolder:
   '/Applications/Zcoin Client.app/Contents/Resources/app.asar.unpacked',
  zcoindPath:
   '/Applications/Zcoin Client.app/Contents/Resources/app.asar.unpacked/assets/core/darwin/zcoind',
  userDataPath: '/Users/spaz/Library/Application Support/zcoin-client' }
2019-08-21T06:50:51.554Z [zcoin:core:manager] info: setting up a new PidManager for zcoind
2019-08-21T06:50:51.555Z [zcoin:core:manager] debug: auto start disabled
2019-08-21T06:50:51.700Z [zcoin:main] info: ---- Starting Zcoin client ----
2019-08-21T06:50:51.701Z [zcoin:i18n] info: setting up languages
2019-08-21T06:50:51.702Z [zcoin:appSettings] info: application settings path /Users/spaz/Library/Application Support/zcoin-client/Settings
2019-08-21T06:50:51.703Z [zcoin:appSettings] info: populating application settings store: SET_APP_VERSION : '0.0.1'
2019-08-21T06:50:51.704Z [zcoin:appSettings] info: populating application settings store: SET_BLOCKCHAIN_LOCATION : '/Users/spaz/Library/Application Support/zcoin'
2019-08-21T06:50:51.704Z [zcoin:store:app] info: setting blockchain location to /Users/spaz/Library/Application Support/zcoin
2019-08-21T06:50:51.705Z [zcoin:appSettings] info: populating application settings store: SET_LOCALE : 'de'
2019-08-21T06:50:51.706Z [zcoin:store:settings] debug: given locale "de" does not exist in available locales list: 
2019-08-21T06:50:51.706Z [zcoin:main] info: path to zcoind binary: /Applications/Zcoin Client.app/Contents/Resources/app.asar.unpacked/assets/core/darwin/zcoind
2019-08-21T06:50:51.706Z [zcoin:core:manager] info: starting child process "zcoind" ...
2019-08-21T06:50:51.710Z [zcoin:i18n] info: current locale: en
2019-08-21T06:50:51.715Z [zcoin:menu] info: setting application menu
2019-08-21T06:50:51.770Z [zcoin:core:manager] debug: daemon is not running
2019-08-21T06:50:51.771Z [zcoin:core:manager] debug: spawning with arguments [ '-clientapi=1',
  '-datadir=/Users/spaz/Library/Application Support/zcoin',
  [length]: 2 ]
2019-08-21T06:50:51.777Z [zcoin:main] info: starting network
2019-08-21T06:50:51.778Z [zcoin:network] info: connected
2019-08-21T06:50:51.778Z [zcoin:network] info: getting api status
2019-08-21T06:50:51.779Z [zcoin:core:manager] info: started daemon process
2019-08-21T06:50:53.157Z [zcoin:store:main] info: [background] vuex connected
2019-08-21T06:50:53.203Z [zcoin:i18n] info: current locale: en
2019-08-21T06:50:53.223Z [zcoin:daemon] debug: Trying to acquire requestMutex for initial/paymentRequest call
2019-08-21T06:50:53.223Z [zcoin:daemon] debug: Trying to acquire requestMutex for initial/stateWallet call
2019-08-21T06:50:53.225Z [zcoin:i18n] info: current locale: en
2019-08-21T06:50:53.257Z [vue:] debug: welcome,location,settingUpLocation,lock,restart
```

**Comment by sproxet** [comment] 2019-08-21 09:43
@catchingknives Do you have zcoind's debug.log available?

**Comment by catchingknives** [comment] 2019-08-21 17:09
Moved to chat

**Comment by sproxet** [comment] 2019-08-21 18:01
This is due to the shipped zcoind dynamically linking a different version of libevent than the one you have available. Next release should switch to static linking.

**Comment by catchingknives** [comment] 2019-08-27 09:49
Solved in latest beta

**Comment by riordant** [comment] 2019-08-27 10:05
Leaving open until release is put out

**Comment by riordant** [comment] 2019-08-30 11:42
Added in `0.0.2`

**Comment by riordant** [comment] 2019-09-08 09:57
Reopening this as I am experiencing it now. 
Steps to reproduce:
- No/empty `zcoin-client` folder
- No/empty regtest folder
- Start client, select default location
- Client shows "Loading blockchain"
- daemon is running in the background + the API is on, as evidenced from the logs.
On restart, I am asked for my password, and this results in issue https://github.com/zcoinofficial/zcoin-client/issues/51.

**Comment by riordant** [comment] 2019-09-08 10:16
Closing to open as a new issue.

**Closed by riordant** 2019-09-08 10:16 UTC
