### ISSUE TITLE
Add setting to restart with a different datadir

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#48] opened 2019-09-03 09:26 UTC
From the forums:
```
Will be good to add settings to choose path to folder with data.
It will not need to download everything from scratch so it could use data from the old client.
```

This can be invoked with the `datadir` conf setting on a restart.

**Comment by sproxet** [comment] 2019-10-31 01:24
This is a duplicate of #102, which has been closed.

**Closed by sproxet** 2019-10-31 01:24 UTC
Labels: Priority 3, enhancement
